### ISSUE TITLE
Task 02: Yêu cầu về chức năng

### ISSUE THREAD

**Issue by linhtp2000** [chanh2000kh/ProjectSE#7]
Mô tả của chức năng hoặc dịch vụ của phần mềm

**Comment by chanh2000kh** [comment]
Các yêu cầu về chức năng:
1. Đăng ký và đăng nhập/ đăng xuất tài khoản/ đăng nhập với tài khoản khách
2. Khai báo các thông tin cơ bản như : cân nặng, giới tính, độ tuổi, mong muốn giảm hay tăng cân,..
3. Tính toán và đưa ra lời khuyên nên tiêu thu bao nhiêu calo mỗi ngày từ những thông tin mà khách hàng đã cho
4. Cho khách hàng tự đưa ra thực đơn của mỗi bữa ăn hằng ngày và tính toán tổng số calo của thực đơn
5. Các chức năng thêm: Như cập nhật tin tức về sức khỏe, chế độ ăn và kết bạn với nhau để trao đổi thông tin, trò chuyện
