### ISSUE TITLE
Task 03: Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by linhtp2000** [chanh2000kh/ProjectSE#8]
Chỉ ra những quy định về tính chất và ràng buộc cho phần mềm hay hệ thống.

**Comment by ngoclam9200** [comment]
1. Đảm bảo thông tin người dùng (tên, tuổi , cân nặng,..)
2. Tính lượng calo cần thiết của người dùng ứng dụng , đảm bảo chế độ dinh dưỡng phù hợp 
3. Khi nhập tuổi người dùng chỉ cho phép nhập 2 chữ số
4. Khi nhập chiều cao , cân nặng người dùng chỉ được phép nhập tối đa chiều cao là 300cm và 300kg
5. Đưa ra chế độ dinh dưỡng phù hợp với tình trạng sức khỏe, chiều cao , cân nặng , mục tiêu hướng tới của người dùng
6. Khi người dùng muốn chọn 1 chế độ dinh dưỡng khác , thì hệ thống sẽ không đưa ra chế độ dinh dưỡng đã tồn tại trong plan của người dùng 
7. Đưa ra thông báo giờ ăn một cách chính xác
8. Cung cấp thông tin dinh dưỡng đầy đủ và chính xác
9. Tính thể trạng cơ thể chi tiết và chính xác

**Comment by linhtp2000** [comment]
10. Bảo mật thông tin người dùng.
11. Tốc độ truy cập cập tối đa 1s.
12.  Người sử dụng chương trình: được cấp username và password và được phân quyền sử dụng chương trình, giúp người quản lý có thể theo dõi, kiểm soát được chương trình, tránh các hợp sửa đổi thông tin không thuộc phạm vi quyền hạn.
13. Password của người sử dụng được mã hóa trước khi ghi vào dữ liệu và người sử dụng có thể đổi password của mình.
14. Chạy ổn định trên các trên các thiết bị đơn giản: điện thoại, máy tính,...
